### ISSUE TITLE
Feature request : Json Prettify

### ISSUE THREAD

**Issue by tryadelion** [WarrenFaith/pidcat#1]
It would be a nice addition if we could enable by params (or it be default) to see Json strings prettified.

**Comment by WarrenFaith** [comment]
Basically the idea is good but there are some problems and I am not sure if this is worth it:
1. regex to find a json string inside a message is not easily done in python. I read about re2 package that is capable of recursive regex but I couldn't manage to get it to work
2. the default Log class and most json libraries already provide functionality like toString(int) to make indented json output

So after some evaluation I feel like it is not worth the work. Feel free to help out :)
